//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XuatExcelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HCC
    {
        public string SO_CT { get; set; }
        public string TEN_NGUOI_GUI { get; set; }
        public string DIA_CHI { get; set; }
        public string SO_HS_HCC { get; set; }
        public System.DateTime NGAY_HEN { get; set; }
        public System.DateTime NGAY_NHAN { get; set; }
        public string TINH_NHAN { get; set; }
        public string HUYEN_NHAN { get; set; }
        public string XA_NHAN { get; set; }
        public string CUOC { get; set; }
        public string SO_HS_KEM { get; set; }
        public string DIEN_THOAI { get; set; }
        public string MA_LOAI_HS { get; set; }
        public string TRONG_LUONG { get; set; }
        public string MA_BUUGUI { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual LOAI_HS LOAI_HS { get; set; }
    }
}
